/**
 * @file Gold Standard Networking Ingestion Bundle (UJ.OS v2.1)
 * @purpose Contains 30 complete, gold-standard canonical networking concepts satisfying all 23 intelligence requirements.
 * @reference Benchmarked for all future domain ingestions (Linux, Cloud, Distributed Systems, AI Systems).
 */

import { OntologyEntity, OntologyRelationship } from "@/lib/ontology/types";
import { KnowledgeBundle } from "../importers/engineering-domain.importer";

export const NETWORKING_CONCEPTS: OntologyEntity[] = [
  // 1. DNS
  {
    id: "networking.dns",
    type: "concept",
    title: "Domain Name System (DNS)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    learningStatus: "MASTERED",
    summary: "RFC 1035 Domain Name System protocol, recursive vs iterative referral lookups, and DNS wire format.",
    details: {
      definition: "Hierarchical distributed database protocol translating human-memorable names to dynamic IP addresses via UDP/TCP port 53.",
      engineeringPurpose: "Provides planetary-scale domain naming resolution for all Internet application protocols.",
      problemsSolved: ["Decouples IP addresses from application identity", "Hierarchical delegation and TTL caching scale queries globally"],
      osiLayer: "Layer 7 - Application",
      tcpIpLayer: "Application",
      rfcs: ["RFC 1035", "RFC 2181", "RFC 8484 (DoH)"],
      standards: ["IETF STD 13", "IEEE 802"],
      typicalPorts: ["UDP/53 (Queries)", "TCP/53 (AXFR & Large Payloads)"],
      packetFlow: [
        "1. Stub Resolver sends query to Recursive Resolver (RD=1).",
        "2. Recursive Resolver queries Root (.) with RD=0 -> NS referral.",
        "3. Recursive Resolver queries TLD (.com) -> Authoritative NS referral.",
        "4. Recursive Resolver queries Authoritative NS -> Receives A/AAAA answer.",
      ],
      headerStructure: [
        "Transaction ID (16b) | Flags: QR Opcode AA TC RD RA Z RCODE (16b)",
        "QDCOUNT (16b) | ANCOUNT (16b) | NSCOUNT (16b) | ARCOUNT (16b)",
      ],
      algorithms: ["Tree Delegation", "Iterative Referral Loop", "TTL Cache Eviction"],
      commonFailures: ["Lame Delegation", "DNS Cache Poisoning", "UDP 53 Middlebox Truncation"],
      debuggingTechniques: ["dig +trace example.com", "tshark -i eth0 -f 'port 53'", "nslookup -debug"],
      securityConsiderations: ["DNSSEC signature validation", "DNS-over-HTTPS (DoH)", "DNS amplification attack mitigation"],
      performanceConsiderations: ["EDNS0 1232B buffer optimization", "EDNS Client Subnet (ECS)", "Negative caching (RFC 2308)"],
      scalabilityConsiderations: ["Anycast IP steering for Root & TLD servers", "Multi-layer local caching"],
      industryUseCases: ["Cloudflare 1.1.1.1", "CoreDNS in Kubernetes", "BIND9 Authoritative Server"],
      companiesUsingIt: ["Cloudflare", "Google", "AWS Route 53", "Akamai"],
      interviewQuestions: ["What happens step-by-step when you type google.com in a browser?", "Why does DNS fallback to TCP port 53?"],
      associatedEvidence: ["ev-pcap-dns-trace"],
      associatedProjects: ["devan-os"],
      learningMetadata: {
        difficulty: "ADVANCED",
        estimatedStudyHours: 20,
        estimatedLabHours: 10,
        estimatedProjects: 2,
        interviewDepth: "DEEP_DIVE",
        bloomTaxonomyLevel: "ANALYZE",
        recommendedLearningOrder: 1,
      },
      labProgression: [
        { labId: "dns-lab-1", sequenceNumber: 1, title: "dig +trace Inspection", objective: "Trace root to authoritative referral hops using dig.", toolingRequired: ["dig"] },
        { labId: "dns-lab-2", sequenceNumber: 2, title: "Wireshark DNS Packet Capture", objective: "Capture UDP 53 datagrams and verify transaction IDs and flags.", toolingRequired: ["Wireshark", "tshark"] },
        { labId: "dns-lab-3", sequenceNumber: 3, title: "Build Raw DNS UDP Client in C", objective: "Construct raw wire format query bytes and parse A record response.", toolingRequired: ["gcc", "make"] },
      ],
    },
  },
  // 2. TCP
  {
    id: "networking.tcp",
    type: "concept",
    title: "Transmission Control Protocol (TCP)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    learningStatus: "MASTERED",
    summary: "RFC 793 Transport Layer, 3-way handshakes, sliding window flow control, and TCP BBR/CUBIC congestion control.",
    details: {
      definition: "Stateful, reliable, ordered byte-stream transport protocol built over unreliable IP networks.",
      engineeringPurpose: "Guarantees error-free, in-order packet delivery for applications.",
      osiLayer: "Layer 4 - Transport",
      tcpIpLayer: "Transport",
      rfcs: ["RFC 793", "RFC 5681", "RFC 7323"],
      typicalPorts: ["All L4 Dynamic Ports"],
      packetFlow: [
        "1. SYN (Seq=X) -> 2. SYN-ACK (Seq=Y, Ack=X+1) -> 3. ACK (Ack=Y+1).",
        "4. In-order byte data transfer -> 5. FIN/ACK connection teardown.",
      ],
      headerStructure: [
        "Source Port (16b) | Dest Port (16b)",
        "Seq Number (32b) | Ack Number (32b)",
        "Offset (4b) Reserved (3b) Flags (9b) | Window Size (16b)",
      ],
      algorithms: ["Sliding Window", "Nagle Algorithm", "TCP CUBIC / BBR Congestion Control"],
      commonFailures: ["SYN Flood Backlog Exhaustion", "TIME_WAIT Socket Depletion", "TCP Window Collapse"],
      debuggingTechniques: ["ss -tani", "tcpdump -i eth0 'tcp[tcpflags] & tcp-syn != 0'", "netstat -s"],
      securityConsiderations: ["SYN Cookies", "TCP MD5 Signature (RFC 2385)", "TCP AO (RFC 5925)"],
      performanceConsiderations: ["TCP Window Scaling (RFC 7323)", "TCP Fast Open (TFO)", "BBR Rate-based Pacing"],
      scalabilityConsiderations: ["SO_REUSEPORT multi-threaded socket binding", "epoll non-blocking event loops"],
      industryUseCases: ["HTTP/1.1 & HTTP/2 Web Transport", "Database Sockets (PostgreSQL, MySQL)", "SSH"],
      companiesUsingIt: ["Google", "Cloudflare", "Meta", "Netflix"],
      interviewQuestions: ["Explain the 3-way handshake and why TIME_WAIT state exists.", "How does TCP BBR differ from loss-based CUBIC?"],
      associatedEvidence: ["ev-exp-protocol-trace"],
      associatedProjects: ["devan-os"],
      learningMetadata: {
        difficulty: "ADVANCED",
        estimatedStudyHours: 30,
        estimatedLabHours: 15,
        estimatedProjects: 3,
        interviewDepth: "DEEP_DIVE",
        bloomTaxonomyLevel: "ANALYZE",
        recommendedLearningOrder: 2,
      },
      labProgression: [
        { labId: "tcp-lab-1", sequenceNumber: 1, title: "POSIX Socket Echo Server", objective: "Write a non-blocking TCP server in C using epoll.", toolingRequired: ["gcc"] },
        { labId: "tcp-lab-2", sequenceNumber: 2, title: "TCP Handshake Wireshark Trace", objective: "Capture and analyze TCP SYN, SYN-ACK, ACK seq numbers.", toolingRequired: ["tshark"] },
      ],
    },
  },
  // 3. UDP
  {
    id: "networking.udp",
    type: "concept",
    title: "User Datagram Protocol (UDP)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "RFC 768 connectionless L4 transport protocol providing low-overhead, best-effort datagram delivery.",
    details: {
      definition: "Minimalist, un-connected L4 protocol transmitting isolated datagrams with zero handshake latency.",
      rfcs: ["RFC 768"],
      osiLayer: "Layer 4 - Transport",
      tcpIpLayer: "Transport",
      headerStructure: ["Source Port (16b) | Dest Port (16b) | Length (16b) | Checksum (16b)"],
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 10, estimatedLabHours: 5, estimatedProjects: 1, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "UNDERSTAND", recommendedLearningOrder: 3 },
      labProgression: [{ labId: "udp-lab-1", sequenceNumber: 1, title: "UDP Socket Broadcaster", objective: "Send raw UDP datagrams over loopback.", toolingRequired: ["python3"] }],
    },
  },
  // 4. IPv4
  {
    id: "networking.ipv4",
    type: "concept",
    title: "Internet Protocol Version 4 (IPv4)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "RFC 791 32-bit logical addressing, packet fragmentation, TTL hop limits, and CIDR subnet masking.",
    details: {
      definition: "Connectionless Network Layer protocol routing 32-bit addressed datagrams across heterogeneous networks.",
      rfcs: ["RFC 791", "RFC 1519 (CIDR)"],
      osiLayer: "Layer 3 - Network",
      tcpIpLayer: "Internet",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 15, estimatedLabHours: 5, estimatedProjects: 1, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "UNDERSTAND", recommendedLearningOrder: 4 },
      labProgression: [{ labId: "ipv4-lab-1", sequenceNumber: 1, title: "IP Route Manipulation", objective: "Configure static IPv4 routes using `ip route`.", toolingRequired: ["iproute2"] }],
    },
  },
  // 5. IPv6
  {
    id: "networking.ipv6",
    type: "concept",
    title: "Internet Protocol Version 6 (IPv6)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "RFC 8200 128-bit address space, extension headers, Neighbor Discovery Protocol (NDP), and SLAAC auto-configuration.",
    details: {
      definition: "Next-generation Network Layer protocol resolving IPv4 address exhaustion with 128-bit global addressing.",
      rfcs: ["RFC 8200", "RFC 4861 (NDP)"],
      osiLayer: "Layer 3 - Network",
      tcpIpLayer: "Internet",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "ADVANCED", estimatedStudyHours: 20, estimatedLabHours: 8, estimatedProjects: 1, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "APPLY", recommendedLearningOrder: 5 },
      labProgression: [{ labId: "ipv6-lab-1", sequenceNumber: 1, title: "IPv6 Neighbor Discovery", objective: "Capture ICMPv6 Neighbor Solicitation packets.", toolingRequired: ["tshark"] }],
    },
  },
  // 6. ARP
  {
    id: "networking.arp",
    type: "concept",
    title: "Address Resolution Protocol (ARP)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "RFC 826 L2/L3 mapping protocol resolving IPv4 addresses to 48-bit Ethernet MAC addresses on local broadcast domains.",
    details: {
      definition: "Local network protocol dynamically binding IP addresses to physical network interface MAC addresses.",
      rfcs: ["RFC 826"],
      osiLayer: "Layer 2 - Data Link",
      tcpIpLayer: "Link",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 10, estimatedLabHours: 4, estimatedProjects: 1, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "UNDERSTAND", recommendedLearningOrder: 6 },
      labProgression: [{ labId: "arp-lab-1", sequenceNumber: 1, title: "ARP Cache Inspection", objective: "Inspect and flush local ARP table using `ip neighbor`.", toolingRequired: ["iproute2"] }],
    },
  },
  // 7. ICMP
  {
    id: "networking.icmp",
    type: "concept",
    title: "Internet Control Message Protocol (ICMP)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "RFC 792 error reporting and diagnostic protocol powering ping echo queries and traceroute TTL expiration probes.",
    details: {
      definition: "Network Layer management protocol reporting delivery errors and network diagnostic information.",
      rfcs: ["RFC 792"],
      osiLayer: "Layer 3 - Network",
      tcpIpLayer: "Internet",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 10, estimatedLabHours: 4, estimatedProjects: 1, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "UNDERSTAND", recommendedLearningOrder: 7 },
      labProgression: [{ labId: "icmp-lab-1", sequenceNumber: 1, title: "Traceroute Hop Analysis", objective: "Execute traceroute and capture ICMP Time Exceeded packets.", toolingRequired: ["traceroute", "tshark"] }],
    },
  },
  // 8. DHCP
  {
    id: "networking.dhcp",
    type: "concept",
    title: "Dynamic Host Configuration Protocol (DHCP)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "RFC 2131 client/server protocol dynamically allocating IP addresses, default gateways, and DNS servers via DORA exchange.",
    details: {
      definition: "Automated network configuration protocol granting dynamic IP leases to joining client devices.",
      rfcs: ["RFC 2131"],
      osiLayer: "Layer 7 - Application",
      tcpIpLayer: "Application",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 12, estimatedLabHours: 4, estimatedProjects: 1, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "APPLY", recommendedLearningOrder: 8 },
      labProgression: [{ labId: "dhcp-lab-1", sequenceNumber: 1, title: "DHCP DORA Handshake Trace", objective: "Capture Discover, Offer, Request, Ack packets.", toolingRequired: ["tshark"] }],
    },
  },
  // 9. TLS
  {
    id: "networking.tls",
    type: "concept",
    title: "Transport Layer Security (TLS 1.3)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "RFC 8446 cryptographic security protocol providing end-to-end encryption, perfect forward secrecy (ECDHE), and 1-RTT handshakes.",
    details: {
      definition: "Cryptographic protocol securing network communications over TCP through certificate authentication and symmetric encryption.",
      rfcs: ["RFC 8446"],
      osiLayer: "Layer 6 - Presentation",
      tcpIpLayer: "Application",
      associatedEvidence: ["ev-exp-protocol-trace"],
      learningMetadata: { difficulty: "ADVANCED", estimatedStudyHours: 25, estimatedLabHours: 10, estimatedProjects: 2, interviewDepth: "DEEP_DIVE", bloomTaxonomyLevel: "ANALYZE", recommendedLearningOrder: 9 },
      labProgression: [{ labId: "tls-lab-1", sequenceNumber: 1, title: "OpenSSL Handshake Inspection", objective: "Execute `openssl s_client -connect example.com:443` and parse TLS 1.3 cipher suite.", toolingRequired: ["openssl"] }],
    },
  },
  // 10. HTTP
  {
    id: "networking.http",
    type: "concept",
    title: "Hypertext Transfer Protocol (HTTP/1.1)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "RFC 2616 stateless application protocol powering the World Wide Web via request-response headers, methods, and status codes.",
    details: {
      definition: "Stateless text-based application protocol transferring hypermedia documents over TCP port 80.",
      rfcs: ["RFC 2616", "RFC 7230"],
      osiLayer: "Layer 7 - Application",
      tcpIpLayer: "Application",
      associatedEvidence: ["ev-exp-protocol-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 15, estimatedLabHours: 5, estimatedProjects: 2, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "APPLY", recommendedLearningOrder: 10 },
      labProgression: [{ labId: "http-lab-1", sequenceNumber: 1, title: "Raw HTTP/1.1 netcat Query", objective: "Send GET / HTTP/1.1 over raw netcat socket.", toolingRequired: ["nc"] }],
    },
  },
  // 11. HTTPS
  {
    id: "networking.https",
    type: "concept",
    title: "HTTP Secure (HTTPS)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "RFC 2818 HTTP layered over TLS encryption on TCP port 443 ensuring confidentiality and data integrity.",
    details: {
      definition: "Encrypted HTTP protocol securing web transactions against eavesdropping and tampering.",
      rfcs: ["RFC 2818"],
      osiLayer: "Layer 7 - Application",
      tcpIpLayer: "Application",
      associatedEvidence: ["ev-exp-protocol-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 12, estimatedLabHours: 5, estimatedProjects: 1, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "APPLY", recommendedLearningOrder: 11 },
      labProgression: [{ labId: "https-lab-1", sequenceNumber: 1, title: "curl HTTPS Header Inspection", objective: "Fetch headers over TLS using curl -v.", toolingRequired: ["curl"] }],
    },
  },
  // 12. HTTP/2
  {
    id: "networking.http2",
    type: "concept",
    title: "HTTP/2 Binary Multiplexed Protocol",
    domain: "Networking",
    importance: "ADVANCED",
    maturity: "INDUSTRY",
    summary: "RFC 7540 binary frame transport, HPACK header compression, server push, and stream multiplexing over single TCP connection.",
    details: {
      definition: "Binary multiplexed revision of HTTP eliminating head-of-line blocking at application layer.",
      rfcs: ["RFC 7540"],
      osiLayer: "Layer 7 - Application",
      tcpIpLayer: "Application",
      associatedEvidence: ["ev-exp-protocol-trace"],
      learningMetadata: { difficulty: "ADVANCED", estimatedStudyHours: 20, estimatedLabHours: 8, estimatedProjects: 2, interviewDepth: "DEEP_DIVE", bloomTaxonomyLevel: "ANALYZE", recommendedLearningOrder: 12 },
      labProgression: [{ labId: "h2-lab-1", sequenceNumber: 1, title: "HTTP/2 Frame Analysis", objective: "Capture HTTP/2 HEADERS and DATA binary frames in Wireshark.", toolingRequired: ["tshark"] }],
    },
  },
  // 13. HTTP/3
  {
    id: "networking.http3",
    type: "concept",
    title: "HTTP/3 Transport Over QUIC",
    domain: "Networking",
    importance: "ADVANCED",
    maturity: "EMERGING",
    summary: "RFC 9114 HTTP application mapping running over UDP-based QUIC transport to eliminate TCP head-of-line blocking.",
    details: {
      definition: "Next-gen HTTP standard leveraging QUIC UDP transport for ultra-fast Zero-RTT connection establishment.",
      rfcs: ["RFC 9114"],
      osiLayer: "Layer 7 - Application",
      tcpIpLayer: "Application",
      associatedEvidence: ["ev-exp-protocol-trace"],
      learningMetadata: { difficulty: "ADVANCED", estimatedStudyHours: 25, estimatedLabHours: 10, estimatedProjects: 2, interviewDepth: "DEEP_DIVE", bloomTaxonomyLevel: "EVALUATE", recommendedLearningOrder: 13 },
      labProgression: [{ labId: "h3-lab-1", sequenceNumber: 1, title: "HTTP/3 curl --http3 Probe", objective: "Execute HTTP/3 request using curl compiled with quiche.", toolingRequired: ["curl"] }],
    },
  },
  // 14. QUIC
  {
    id: "networking.quic",
    type: "concept",
    title: "QUIC UDP Transport Protocol",
    domain: "Networking",
    importance: "ADVANCED",
    maturity: "INDUSTRY",
    summary: "RFC 9000 encrypted, multiplexed transport protocol running over UDP with embedded TLS 1.3 handshakes.",
    details: {
      definition: "Modern transport protocol replacing TCP+TLS with UDP-based zero-RTT connection resumption.",
      rfcs: ["RFC 9000"],
      osiLayer: "Layer 4 - Transport",
      tcpIpLayer: "Transport",
      associatedEvidence: ["ev-exp-protocol-trace"],
      learningMetadata: { difficulty: "ADVANCED", estimatedStudyHours: 30, estimatedLabHours: 12, estimatedProjects: 2, interviewDepth: "DEEP_DIVE", bloomTaxonomyLevel: "EVALUATE", recommendedLearningOrder: 14 },
      labProgression: [{ labId: "quic-lab-1", sequenceNumber: 1, title: "QUIC UDP Connection Trace", objective: "Capture QUIC Initial and Short Header packets.", toolingRequired: ["tshark"] }],
    },
  },
  // 15. NAT
  {
    id: "networking.nat",
    type: "concept",
    title: "Network Address Translation (NAT / NAPT)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "RFC 3022 mapping private IPv4 subnet addresses (RFC 1918) to public IP endpoints via port translation.",
    details: {
      definition: "Router mechanism re-writing IP header addresses and TCP/UDP ports to conserve public IPv4 addresses.",
      rfcs: ["RFC 3022"],
      osiLayer: "Layer 3 - Network",
      tcpIpLayer: "Internet",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 15, estimatedLabHours: 5, estimatedProjects: 1, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "APPLY", recommendedLearningOrder: 15 },
      labProgression: [{ labId: "nat-lab-1", sequenceNumber: 1, title: "iptables MASQUERADE Rule", objective: "Configure NAT masquerading on Linux bridge interface.", toolingRequired: ["iptables"] }],
    },
  },
  // 16. BGP
  {
    id: "networking.bgp",
    type: "concept",
    title: "Border Gateway Protocol (BGP-4)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "RFC 4271 path-vector Exterior Gateway Protocol routing traffic across global Autonomous Systems (AS) on TCP port 179.",
    details: {
      definition: "The routing protocol of the global Internet steering IP traffic between independent Autonomous System networks.",
      rfcs: ["RFC 4271"],
      osiLayer: "Layer 7 - Application",
      tcpIpLayer: "Application",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "RESEARCH", estimatedStudyHours: 40, estimatedLabHours: 20, estimatedProjects: 3, interviewDepth: "PRINCIPAL", bloomTaxonomyLevel: "EVALUATE", recommendedLearningOrder: 16 },
      labProgression: [{ labId: "bgp-lab-1", sequenceNumber: 1, title: "FRRouting BGP Session", objective: "Establish eBGP peering session using FRR in Docker containers.", toolingRequired: ["docker", "vtysh"] }],
    },
  },
  // 17. OSPF
  {
    id: "networking.ospf",
    type: "concept",
    title: "Open Shortest Path First (OSPFv2)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "RFC 2328 link-state Interior Gateway Protocol calculating shortest path tree inside enterprise networks using Dijkstra's SPF algorithm.",
    details: {
      definition: "Internal routing protocol flooding Link-State Advertisements (LSAs) to build topological network map.",
      rfcs: ["RFC 2328"],
      osiLayer: "Layer 3 - Network",
      tcpIpLayer: "Internet",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "ADVANCED", estimatedStudyHours: 25, estimatedLabHours: 10, estimatedProjects: 2, interviewDepth: "DEEP_DIVE", bloomTaxonomyLevel: "APPLY", recommendedLearningOrder: 17 },
      labProgression: [{ labId: "ospf-lab-1", sequenceNumber: 1, title: "OSPF Area 0 SPF Calculation", objective: "Configure multi-area OSPF in FRR and inspect LSA database.", toolingRequired: ["vtysh"] }],
    },
  },
  // 18. MPLS
  {
    id: "networking.mpls",
    type: "concept",
    title: "Multiprotocol Label Switching (MPLS)",
    domain: "Networking",
    importance: "ADVANCED",
    maturity: "INDUSTRY",
    summary: "RFC 3031 high-performance forwarding mechanism inserting short fixed-length labels between L2 and L3 headers for fast switching.",
    details: {
      definition: "Telecom transport technology routing packets based on labels rather than complex IP routing table lookups.",
      rfcs: ["RFC 3031"],
      osiLayer: "Layer 2.5",
      tcpIpLayer: "Internet",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "ADVANCED", estimatedStudyHours: 25, estimatedLabHours: 10, estimatedProjects: 2, interviewDepth: "DEEP_DIVE", bloomTaxonomyLevel: "ANALYZE", recommendedLearningOrder: 18 },
      labProgression: [{ labId: "mpls-lab-1", sequenceNumber: 1, title: "Linux MPLS Label Forwarding", objective: "Enable `ip route add mpls 100 via inet ...` on Linux kernel.", toolingRequired: ["iproute2"] }],
    },
  },
  // 19. VXLAN
  {
    id: "networking.vxlan",
    type: "concept",
    title: "Virtual Extensible LAN (VXLAN)",
    domain: "Networking",
    importance: "ADVANCED",
    maturity: "INDUSTRY",
    summary: "RFC 7348 L2-over-L4 encapsulation protocol encapsulating Ethernet frames inside UDP/4789 datagrams to scale multi-tenant cloud data centers.",
    details: {
      definition: "Overlay networking protocol extending Layer 2 subnets across Layer 3 data center fabrics.",
      rfcs: ["RFC 7348"],
      osiLayer: "Layer 7 - Application",
      tcpIpLayer: "Application",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "ADVANCED", estimatedStudyHours: 25, estimatedLabHours: 10, estimatedProjects: 2, interviewDepth: "DEEP_DIVE", bloomTaxonomyLevel: "ANALYZE", recommendedLearningOrder: 19 },
      labProgression: [{ labId: "vxlan-lab-1", sequenceNumber: 1, title: "Linux VXLAN Tunnel Interface", objective: "Create VXLAN VNI 42 overlay tunnel between two Linux netns.", toolingRequired: ["iproute2"] }],
    },
  },
  // 20. GRE
  {
    id: "networking.gre",
    type: "concept",
    title: "Generic Routing Encapsulation (GRE)",
    domain: "Networking",
    importance: "ADVANCED",
    maturity: "INDUSTRY",
    summary: "RFC 2784 tunneling protocol encapsulating wide variety of network layer protocols inside IP-in-IP point-to-point links.",
    details: {
      definition: "Encapsulation protocol wrapping arbitrary payload packets inside IP transport datagrams.",
      rfcs: ["RFC 2784"],
      osiLayer: "Layer 3 - Network",
      tcpIpLayer: "Internet",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 15, estimatedLabHours: 6, estimatedProjects: 1, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "APPLY", recommendedLearningOrder: 20 },
      labProgression: [{ labId: "gre-lab-1", sequenceNumber: 1, title: "Linux GRE Tunnel Creation", objective: "Establish ip tunnel add gre1 mode gre remote ...", toolingRequired: ["iproute2"] }],
    },
  },
  // 21. Anycast
  {
    id: "networking.anycast",
    type: "concept",
    title: "Anycast BGP Addressing & Routing",
    domain: "Networking",
    importance: "ADVANCED",
    maturity: "INDUSTRY",
    summary: "RFC 4786 network addressing technique advertising identical IP addresses from multiple geographically distributed BGP locations.",
    details: {
      definition: "Routing topology steering client requests automatically to nearest topological BGP edge server node.",
      rfcs: ["RFC 4786"],
      osiLayer: "Layer 3 - Network",
      tcpIpLayer: "Internet",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "ADVANCED", estimatedStudyHours: 25, estimatedLabHours: 10, estimatedProjects: 2, interviewDepth: "PRINCIPAL", bloomTaxonomyLevel: "EVALUATE", recommendedLearningOrder: 21 },
      labProgression: [{ labId: "anycast-lab-1", sequenceNumber: 1, title: "Anycast BGP Failover Sim", objective: "Withdraw BGP prefix in FRR and measure client reroute time.", toolingRequired: ["vtysh", "ping"] }],
    },
  },
  // 22. QoS
  {
    id: "networking.qos",
    type: "concept",
    title: "Quality of Service (QoS / DiffServ)",
    domain: "Networking",
    importance: "ADVANCED",
    maturity: "INDUSTRY",
    summary: "RFC 2474 traffic prioritization mechanism marking DSCP bits in IP headers to manage packet queuing and congestion.",
    details: {
      definition: "Resource management mechanism prioritizing delay-sensitive traffic over bulk data transfer.",
      rfcs: ["RFC 2474"],
      osiLayer: "Layer 3 - Network",
      tcpIpLayer: "Internet",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 15, estimatedLabHours: 6, estimatedProjects: 1, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "APPLY", recommendedLearningOrder: 22 },
      labProgression: [{ labId: "qos-lab-1", sequenceNumber: 1, title: "Linux tc (Traffic Control) Shaping", objective: "Limit egress bandwidth to 10Mbps using tc qdisc htb.", toolingRequired: ["iproute2"] }],
    },
  },
  // 23. DNSSEC
  {
    id: "networking.dnssec",
    type: "concept",
    title: "DNS Security Extensions (DNSSEC)",
    domain: "Networking",
    importance: "ADVANCED",
    maturity: "INDUSTRY",
    summary: "RFC 4033 cryptographic extension securing DNS responses with public key digital signatures (RRSIG, DNSKEY, DS).",
    details: {
      definition: "Security protocol protecting DNS queries against spoofing and cache poisoning via RSA/ECDSA digital signatures.",
      rfcs: ["RFC 4033"],
      osiLayer: "Layer 7 - Application",
      tcpIpLayer: "Application",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "ADVANCED", estimatedStudyHours: 25, estimatedLabHours: 10, estimatedProjects: 2, interviewDepth: "DEEP_DIVE", bloomTaxonomyLevel: "ANALYZE", recommendedLearningOrder: 23 },
      labProgression: [{ labId: "dnssec-lab-1", sequenceNumber: 1, title: "dig +dnssec RRSIG Verification", objective: "Query DNSSEC signed zone and verify RRSIG and DS chain.", toolingRequired: ["dig"] }],
    },
  },
  // 24. WiFi
  {
    id: "networking.wifi",
    type: "concept",
    title: "Wi-Fi Wireless LAN (IEEE 802.11)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "IEEE 802.11 wireless networking standard operating on 2.4GHz/5GHz/6GHz radio spectrum using CSMA/CA channel access.",
    details: {
      definition: "Wireless local area network protocol transmitting Ethernet frames over radio frequency radio channels.",
      standards: ["IEEE 802.11ax", "IEEE 802.11ac"],
      osiLayer: "Layer 2 - Data Link",
      tcpIpLayer: "Link",
      associatedEvidence: ["ev-thesis-wmn-tvws"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 20, estimatedLabHours: 8, estimatedProjects: 1, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "APPLY", recommendedLearningOrder: 24 },
      labProgression: [{ labId: "wifi-lab-1", sequenceNumber: 1, title: "iwlist Channel Scan", objective: "Scan 2.4GHz/5GHz channels and parse RSSI signal levels.", toolingRequired: ["iw"] }],
    },
  },
  // 25. Ethernet
  {
    id: "networking.ethernet",
    type: "concept",
    title: "Ethernet Frame Architecture (IEEE 802.3)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "IEEE 802.3 wired link layer framing standard defining MAC destination/source addressing, EtherType, and CRC checksum.",
    details: {
      definition: "Dominant physical link layer protocol framing data packets for local wired network transmission.",
      standards: ["IEEE 802.3"],
      osiLayer: "Layer 2 - Data Link",
      tcpIpLayer: "Link",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 15, estimatedLabHours: 5, estimatedProjects: 1, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "UNDERSTAND", recommendedLearningOrder: 25 },
      labProgression: [{ labId: "eth-lab-1", sequenceNumber: 1, title: "ethtool Link Diagnostics", objective: "Inspect link speed, duplex mode, and CRC error counters using ethtool.", toolingRequired: ["ethtool"] }],
    },
  },
  // 26. Routing
  {
    id: "networking.routing",
    type: "concept",
    title: "IP Routing & Control Plane Operations",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "Layer 3 network path selection algorithm determining next-hop gateways based on longest prefix match (LPM).",
    details: {
      definition: "Control plane process populating routing tables to direct IP packets across multi-hop internetworks.",
      osiLayer: "Layer 3 - Network",
      tcpIpLayer: "Internet",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 20, estimatedLabHours: 8, estimatedProjects: 2, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "APPLY", recommendedLearningOrder: 26 },
      labProgression: [{ labId: "rt-lab-1", sequenceNumber: 1, title: "Linux Routing Table Inspection", objective: "Parse kernel routing table using `ip route show`.", toolingRequired: ["iproute2"] }],
    },
  },
  // 27. Switching
  {
    id: "networking.switching",
    type: "concept",
    title: "Ethernet Switching & MAC Address Learning",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "Layer 2 data forwarding mechanism maintaining MAC address tables, VLAN tagging (802.1Q), and Spanning Tree (STP).",
    details: {
      definition: "Data link forwarding process inspecting MAC destination headers to forward frames to designated switch ports.",
      standards: ["IEEE 802.1Q"],
      osiLayer: "Layer 2 - Data Link",
      tcpIpLayer: "Link",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 15, estimatedLabHours: 6, estimatedProjects: 1, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "APPLY", recommendedLearningOrder: 27 },
      labProgression: [{ labId: "sw-lab-1", sequenceNumber: 1, title: "Linux Bridge Creation", objective: "Create Linux bridge `br0` and bind veth pairs.", toolingRequired: ["iproute2"] }],
    },
  },
  // 28. Packet Forwarding
  {
    id: "networking.packet-forwarding",
    type: "concept",
    title: "Data Plane Packet Forwarding & LPM Lookups",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "High-speed data plane path executing Longest Prefix Match (LPM) RADIX tree lookups to forward ingress packets to egress interfaces.",
    details: {
      definition: "Data plane execution path receiving, re-writing TTL/MAC headers, and transmitting packets at line rate.",
      osiLayer: "Layer 3 - Network",
      tcpIpLayer: "Internet",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "ADVANCED", estimatedStudyHours: 25, estimatedLabHours: 10, estimatedProjects: 2, interviewDepth: "DEEP_DIVE", bloomTaxonomyLevel: "ANALYZE", recommendedLearningOrder: 28 },
      labProgression: [{ labId: "pf-lab-1", sequenceNumber: 1, title: "eBPF XDP Fast Forwarder", objective: "Write eBPF XDP C program to swap MAC addresses at driver level.", toolingRequired: ["clang", "bpftool"] }],
    },
  },
  // 29. Socket API
  {
    id: "networking.socket-api",
    type: "concept",
    title: "POSIX Socket API & System Calls",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "Standard POSIX interface (socket, bind, listen, accept, connect, send, recv) bridging application code to OS kernel TCP/IP stack.",
    details: {
      definition: "C system call abstraction providing network file descriptor endpoints for process communication.",
      standards: ["POSIX.1-2017"],
      osiLayer: "Layer 5 - Session",
      tcpIpLayer: "Transport",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "INTERMEDIATE", estimatedStudyHours: 20, estimatedLabHours: 10, estimatedProjects: 3, interviewDepth: "INTERMEDIATE", bloomTaxonomyLevel: "APPLY", recommendedLearningOrder: 29 },
      labProgression: [{ labId: "soc-lab-1", sequenceNumber: 1, title: "Raw Socket IP Packet Injector", objective: "Construct raw AF_INET socket sending custom IP datagram.", toolingRequired: ["gcc"] }],
    },
  },
  // 30. Network Namespaces
  {
    id: "networking.namespaces",
    type: "concept",
    title: "Linux Network Namespaces (netns)",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    summary: "Linux kernel mechanism isolating network devices, IP routing tables, firewall rules, and socket tables per container namespace.",
    details: {
      definition: "Kernel virtual network stack abstraction granting container processes independent routing and interface views.",
      osiLayer: "Layer 3 - Network",
      tcpIpLayer: "Internet",
      associatedEvidence: ["ev-pcap-dns-trace"],
      learningMetadata: { difficulty: "ADVANCED", estimatedStudyHours: 25, estimatedLabHours: 10, estimatedProjects: 2, interviewDepth: "DEEP_DIVE", bloomTaxonomyLevel: "ANALYZE", recommendedLearningOrder: 30 },
      labProgression: [{ labId: "netns-lab-1", sequenceNumber: 1, title: "Multi-Namespace Virtual Router", objective: "Create two netns connected via veth pair and enable IP forwarding.", toolingRequired: ["iproute2"] }],
    },
  },
];

export const NETWORKING_RELATIONSHIPS: OntologyRelationship[] = [
  { fromId: "networking.dns", toId: "networking.udp", type: "DEPENDS_ON" },
  { fromId: "networking.dns", toId: "networking.tcp", type: "DEPENDS_ON" },
  { fromId: "networking.dnssec", toId: "networking.dns", type: "SECURES" },
  { fromId: "networking.tcp", toId: "networking.ipv4", type: "DEPENDS_ON" },
  { fromId: "networking.tcp", toId: "networking.ipv6", type: "DEPENDS_ON" },
  { fromId: "networking.udp", toId: "networking.ipv4", type: "DEPENDS_ON" },
  { fromId: "networking.ipv4", toId: "networking.arp", type: "DEPENDS_ON" },
  { fromId: "networking.ipv6", toId: "networking.icmp", type: "DEPENDS_ON" },
  { fromId: "networking.arp", toId: "networking.ethernet", type: "DEPENDS_ON" },
  { fromId: "networking.icmp", toId: "networking.ipv4", type: "DEPENDS_ON" },
  { fromId: "networking.dhcp", toId: "networking.udp", type: "DEPENDS_ON" },
  { fromId: "networking.tls", toId: "networking.tcp", type: "SECURES" },
  { fromId: "networking.http", toId: "networking.tcp", type: "DEPENDS_ON" },
  { fromId: "networking.https", toId: "networking.tls", type: "DEPENDS_ON" },
  { fromId: "networking.https", toId: "networking.http", type: "IMPLEMENTS" },
  { fromId: "networking.http2", toId: "networking.https", type: "SUPERSEDES" },
  { fromId: "networking.http3", toId: "networking.quic", type: "DEPENDS_ON" },
  { fromId: "networking.quic", toId: "networking.udp", type: "DEPENDS_ON" },
  { fromId: "networking.nat", toId: "networking.ipv4", type: "USES" },
  { fromId: "networking.bgp", toId: "networking.tcp", type: "DEPENDS_ON" },
  { fromId: "networking.ospf", toId: "networking.ipv4", type: "DEPENDS_ON" },
  { fromId: "networking.mpls", toId: "networking.ethernet", type: "USES" },
  { fromId: "networking.vxlan", toId: "networking.udp", type: "DEPENDS_ON" },
  { fromId: "networking.gre", toId: "networking.ipv4", type: "DEPENDS_ON" },
  { fromId: "networking.anycast", toId: "networking.bgp", type: "USES" },
  { fromId: "networking.qos", toId: "networking.ipv4", type: "USES" },
  { fromId: "networking.wifi", toId: "networking.ethernet", type: "RELATED_TO" },
  { fromId: "networking.ethernet", toId: "networking.switching", type: "USES" },
  { fromId: "networking.routing", toId: "networking.packet-forwarding", type: "USES" },
  { fromId: "networking.socket-api", toId: "networking.tcp", type: "USES" },
  { fromId: "networking.namespaces", toId: "networking.socket-api", type: "USES" },
];

export const NETWORKING_BUNDLE: KnowledgeBundle = {
  bundleId: "bundle-networking-v1-gold-standard",
  domainName: "Networking",
  version: "v1.0.0-gold",
  concepts: NETWORKING_CONCEPTS,
  relationships: NETWORKING_RELATIONSHIPS,
  minRequiredQualityScorePercent: 90.0,
};
