/**
 * @file Canonical Scalable ICT Engineering Canon Topology
 * @purpose Populate representative concepts across all engineering domains with full 30-attribute contracts, classification tiers, capabilities, evidence weights, lifecycle, and professional mapping.
 * @principle Scalable to 3,000 - 5,000 concepts without structural changes.
 */

import type { OntologyEntity, OntologyRelationship } from "./types";

export const CANONICAL_ENTITIES: OntologyEntity[] = [
  // =========================================================================
  // 1. NETWORKING & INTERNET ENGINEERING CONCEPTS
  // =========================================================================
  {
    id: "dns-iterative-resolution",
    type: "concept",
    title: "DNS Iterative Resolution & Protocol Mechanics",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    learningStatus: "MASTERED",
    summary: "RFC 1035 Domain Name System protocol, recursive vs. iterative lookup hops, and DNS wire format datagrams.",
    details: {
      definition: "Hierarchical distributed database protocol translating human-readable hostnames into IP addresses via UDP/TCP port 53.",
      engineeringPurpose: "Provides global naming resolution service underlying all Internet application protocols.",
      problemsSolved: ["Decouples network IP addressing from application identifiers", "Distributed caching scales query volume globally"],
      prerequisites: ["tcp-ip-stack", "posix-sockets"],
      dependents: ["tls-13-handshake", "k8s-cni-networking"],
      relatedConcepts: ["bgp-routing", "dnssec-extensions"],
      standards: ["RFC 1034", "RFC 1035"],
      rfcs: ["RFC 1035", "RFC 2181"],
      algorithms: ["Iterative referral tree traversal", "TTL cache eviction"],
      tools: ["dig", "tshark", "bind9", "unbound"],
      libraries: ["c-ares", "dnspython"],
      operatingSystems: ["Linux", "FreeBSD"],
      languages: ["C", "Go"],
      securityConsiderations: ["Cache poisoning / Kaminsky attacks", "UDP amplification DDoS", "DoH/DoT privacy"],
      performanceConsiderations: ["EDNS0 buffer sizing", "Local resolver caching", "RTT optimization via Anycast"],
      scalabilityConsiderations: ["Hierarchical delegation tree", "Root hints server distribution"],
      debuggingTechniques: ["dig +trace +all", "tshark -i eth0 -f 'port 53' -w dns.pcap"],
      industryUseCases: ["Global CDN traffic steering", "Service discovery in cloud environments"],
      companiesUsingIt: ["Cloudflare", "AWS Route 53", "Google Cloud DNS"],
      interviewTopics: ["What happens when you type google.com?", "Iterative vs recursive DNS lookups", "RD bit RFC semantics"],
      associatedProjects: ["devan-os", "cosmohub"],
      associatedExperiments: ["networking-protocol-pipeline"],
      associatedEvidence: ["pcap-dns-trace", "repo-devan2"],
      competency: { knowledge: 10, experience: 9, evidence: 10, confidence: 9 },
      missionRelevance: ["wireless-mesh-tvws"],
      capabilities: ["OBSERVE", "REMEMBER", "REASON"],
      evidenceStrengthWeight: 0.95,
      lifecycle: {
        introducedDate: "2024-01-15",
        lastReviewedDate: "2026-08-07",
        lastAppliedDate: "2026-08-07",
        lastVerifiedDate: "2026-08-07",
        confidenceDecayRate: 0.01,
      },
      professionalMapping: {
        engineeringRoles: ["Network Systems Architect", "Systems Engineer", "SRE"],
        certifications: ["CCNA", "CCNP Enterprise"],
        interviewDepth: "DEEP_DIVE",
        industrySectors: ["Telecommunications", "Cloud Infrastructure"],
      },
    },
  },
  {
    id: "tcp-ip-stack",
    type: "concept",
    title: "TCP/IP Protocol Stack & POSIX Sockets",
    domain: "Networking",
    importance: "CORE",
    maturity: "INDUSTRY",
    learningStatus: "MASTERED",
    summary: "RFC 793 Transport Layer, 3-way handshakes, window scaling, TCP BBR/CUBIC congestion control, and POSIX sockets.",
    details: {
      definition: "Reliable stream-oriented transport protocol establishing stateful byte-stream communication over unreliable IP networks.",
      engineeringPurpose: "Guarantees in-order, error-checked, flow-controlled packet delivery.",
      problemsSolved: ["Packet loss recovery via ACK retransmission", "Network congestion collapse prevention"],
      prerequisites: ["posix-sockets"],
      dependents: ["tls-13-handshake", "bgp-routing", "raft-consensus"],
      standards: ["RFC 793", "RFC 5681"],
      rfcs: ["RFC 793", "RFC 7323", "RFC 8402"],
      algorithms: ["Jacobson/Karels RTT estimation", "Nagle algorithm", "TCP CUBIC / BBR congestion control"],
      tools: ["wireshark", "ss", "netstat", "iperf3"],
      libraries: ["libuv", "tokio"],
      operatingSystems: ["Linux Kernel", "FreeBSD"],
      languages: ["C", "Rust"],
      securityConsiderations: ["SYN flood DDoS attacks", "TCP sequence prediction / hijacking"],
      performanceConsiderations: ["TCP Window Scaling", "TCP Fast Open (TFO)", "SO_REUSEPORT socket option"],
      scalabilityConsiderations: ["epoll socket multiplexing", "Kernel socket buffer memory limits"],
      debuggingTechniques: ["ss -tina", "tcptrace", "sysctl net.ipv4.tcp_congestion_control"],
      industryUseCases: ["Web server connections", "Database RPC streams", "Financial trading transport"],
      companiesUsingIt: ["Google", "Netflix", "Meta"],
      interviewTopics: ["TCP 3-way handshake & 4-way FIN teardown", "TIME_WAIT state management", "Sliding window protocol"],
      associatedProjects: ["devan-os", "cosmohub"],
      associatedExperiments: ["networking-protocol-pipeline"],
      associatedEvidence: ["repo-devan2"],
      competency: { knowledge: 10, experience: 9, evidence: 9, confidence: 9 },
      capabilities: ["OBSERVE", "REMEMBER", "REASON"],
      evidenceStrengthWeight: 0.95,
      lifecycle: { lastVerifiedDate: "2026-08-07", confidenceDecayRate: 0.01 },
      professionalMapping: {
        engineeringRoles: ["Systems Engineer", "Network Architect"],
        certifications: ["CCNA"],
        interviewDepth: "DEEP_DIVE",
        industrySectors: ["Telecommunications", "FinTech"],
      },
    },
  },
  {
    id: "bgp-routing",
    type: "concept",
    title: "BGP-4 Path Vector Routing & AS Peering",
    domain: "Networking",
    importance: "ADVANCED",
    maturity: "INDUSTRY",
    learningStatus: "PRACTICING",
    summary: "RFC 4271 Border Gateway Protocol, Autonomous System peering, prefix advertising, and path vector selection.",
    details: {
      definition: "Exterior gateway protocol exchanging routing and reachability information among autonomous systems (AS) on the Internet.",
      engineeringPurpose: "Enables inter-domain routing and global Internet connectivity.",
      problemsSolved: ["Global IP address reachability", "Policy-based routing between ISP networks"],
      prerequisites: ["tcp-ip-stack"],
      dependents: ["anycast-routing"],
      standards: ["RFC 4271"],
      rfcs: ["RFC 4271", "RFC 4760"],
      algorithms: ["BGP Best Path Selection algorithm"],
      tools: ["FRRouting (FRR)", "BIRD", "GoBGP"],
      operatingSystems: ["Linux", "Cisco IOS-XE"],
      securityConsiderations: ["BGP route hijacking", "RPKI origin validation"],
      performanceConsiderations: ["Route flap dampening", "BGP prefix aggregation"],
      debuggingTechniques: ["show ip bgp summary", "traceroute -A"],
      companiesUsingIt: ["Cloudflare", "Equinix", "Tier-1 ISPs"],
      interviewTopics: ["BGP path selection criteria", "eBGP vs iBGP", "BGP Communities"],
      competency: { knowledge: 8, experience: 6, evidence: 7, confidence: 7 },
      capabilities: ["REASON", "RECOMMEND"],
      evidenceStrengthWeight: 0.85,
      professionalMapping: {
        engineeringRoles: ["Network Architect", "ISP Systems Engineer"],
        certifications: ["CCNP", "CCIE"],
        interviewDepth: "DEEP_DIVE",
        industrySectors: ["Telecommunications"],
      },
    },
  },
  {
    id: "tvws-rf-propagation",
    type: "concept",
    title: "TV White Space Sub-1GHz RF Propagation",
    domain: "Networking",
    importance: "SPECIALIZED",
    maturity: "RESEARCH",
    learningStatus: "APPLIED",
    summary: "Dynamic spectrum access in 470–698 MHz UHF bands, non-line-of-sight (NLOS) signal diffraction, and terrain occlusion.",
    details: {
      definition: "Unused television broadcast spectrum leveraged for long-range, non-line-of-sight wireless broadband access.",
      engineeringPurpose: "Extends broadband connectivity across rugged, forested, and rural terrain.",
      problemsSolved: ["High RF path loss over hills and foliage", "Expensive fiber deployment in low-density rural areas"],
      prerequisites: ["longley-rice-itm"],
      dependents: ["olsr-mesh-routing", "aodv-mesh-routing"],
      standards: ["IEEE 802.22", "FCC Part 15 Subpart H"],
      tools: ["SDR", "GNU Radio", "Radio Mobile"],
      companiesUsingIt: ["Microsoft Airband Initiative"],
      associatedProjects: ["thesis-wmn-tvws"],
      associatedExperiments: ["tvws-propagation-sim"],
      competency: { knowledge: 9, experience: 8, evidence: 9, confidence: 8 },
      missionRelevance: ["wireless-mesh-tvws"],
      capabilities: ["OBSERVE", "REASON", "EVOLVE"],
      evidenceStrengthWeight: 0.90,
      professionalMapping: {
        engineeringRoles: ["RF Systems Engineer", "Wireless Mesh Researcher"],
        certifications: ["IEEE Wireless Specialist"],
        interviewDepth: "PRINCIPAL",
        industrySectors: ["Telecommunications", "Research"],
      },
    },
  },
  {
    id: "longley-rice-itm",
    type: "concept",
    title: "Longley-Rice (ITM) Irregular Terrain Propagation Modeling",
    domain: "Networking",
    importance: "SPECIALIZED",
    maturity: "ACADEMIC",
    learningStatus: "VERIFIED",
    summary: "Irregular Terrain Model algorithms predicting radio path loss over undulating hills and forest canopy.",
    details: {
      definition: "Mathematical radio propagation model predicting attenuation of RF signals over irregular terrain from 20 MHz to 20 GHz.",
      engineeringPurpose: "Calculates path loss for wireless link budgets in complex geographic terrain.",
      problemsSolved: ["Terrain obstruction diffraction calculation", "Tropospheric scatter loss estimation"],
      associatedProjects: ["thesis-wmn-tvws"],
      competency: { knowledge: 9, experience: 8, evidence: 9, confidence: 8 },
      capabilities: ["REASON"],
      evidenceStrengthWeight: 0.90,
      professionalMapping: {
        engineeringRoles: ["RF Engineer"],
        certifications: [],
        interviewDepth: "DEEP_DIVE",
        industrySectors: ["Telecommunications"],
      },
    },
  },
  {
    id: "olsr-mesh-routing",
    type: "concept",
    title: "OLSR Proactive Wireless Mesh Routing",
    domain: "Networking",
    importance: "ADVANCED",
    maturity: "INDUSTRY",
    learningStatus: "TESTED",
    summary: "RFC 3626 Optimized Link State Routing protocol, Multipoint Relay (MPR) selection, and link-state topology control.",
    details: {
      definition: "Proactive link-state routing protocol optimized for mobile ad hoc networks (MANETs) and wireless mesh networks.",
      engineeringPurpose: "Maintains immediate routing topology across multi-hop wireless nodes.",
      rfcs: ["RFC 3626"],
      associatedProjects: ["thesis-wmn-tvws"],
      competency: { knowledge: 8, experience: 7, evidence: 8, confidence: 8 },
      capabilities: ["REASON", "RECOMMEND"],
      evidenceStrengthWeight: 0.85,
      professionalMapping: {
        engineeringRoles: ["Wireless Network Engineer"],
        certifications: [],
        interviewDepth: "INTERMEDIATE",
        industrySectors: ["Defense", "Telecommunications"],
      },
    },
  },

  // =========================================================================
  // 2. OPERATING SYSTEMS & LINUX KERNEL CONCEPTS
  // =========================================================================
  {
    id: "linux-ebpf-telemetry",
    type: "concept",
    title: "Linux Kernel eBPF Telemetry & Tracing",
    domain: "Operating Systems",
    importance: "CORE",
    maturity: "INDUSTRY",
    learningStatus: "MASTERED",
    summary: "Extended Berkeley Packet Filter, in-kernel bytecode verification, socket kprobes/uprobes, and low-overhead observability.",
    details: {
      definition: "In-kernel virtual machine executing sandboxed bytecode at kernel event hooks without recompiling kernel modules.",
      engineeringPurpose: "Provides ultra-low overhead tracing, network packet filtering, and kernel observability.",
      problemsSolved: ["High overhead of user-space context switches for packet analysis", "Kernel panic risk from custom kernel modules"],
      prerequisites: ["kernel-user-space", "posix-sockets"],
      dependents: ["k8s-cni-networking"],
      tools: ["bpftrace", "cilium", "bcc", "bpftool"],
      operatingSystems: ["Linux Kernel 4.18+"],
      languages: ["C", "Rust", "eBPF bytecode"],
      performanceConsiderations: ["JIT compilation to native CPU instructions", "Ring buffer memory lock minimization"],
      debuggingTechniques: ["bpftool prog dump jited", "cat /sys/kernel/debug/tracing/trace_pipe"],
      companiesUsingIt: ["Meta", "Netflix", "Cilium", "Cloudflare"],
      associatedProjects: ["devan-os"],
      competency: { knowledge: 10, experience: 8, evidence: 9, confidence: 9 },
      capabilities: ["OBSERVE", "REASON", "EVOLVE"],
      evidenceStrengthWeight: 0.95,
      professionalMapping: {
        engineeringRoles: ["Systems Engineer", "Kernel Engineer", "SRE"],
        certifications: ["LFCS"],
        interviewDepth: "DEEP_DIVE",
        industrySectors: ["Cloud Infrastructure", "Security"],
      },
    },
  },
  {
    id: "posix-sockets",
    type: "concept",
    title: "POSIX Socket API & Async I/O Multiplexing",
    domain: "Operating Systems",
    importance: "CORE",
    maturity: "INDUSTRY",
    learningStatus: "MASTERED",
    summary: "Non-blocking sockets, event loop architecture (epoll/kqueue), ring buffers, and zero-copy data transfer.",
    details: {
      definition: "Standard API for network IPC providing file-descriptor interface to transport layer protocols.",
      engineeringPurpose: "Enables concurrent network I/O across thousands of open file descriptors.",
      prerequisites: ["system-calls"],
      dependents: ["tcp-ip-stack", "dns-iterative-resolution"],
      tools: ["strace", "lsof"],
      operatingSystems: ["Linux", "POSIX compliant OS"],
      languages: ["C", "C++", "Rust", "Go"],
      associatedProjects: ["devan-os"],
      competency: { knowledge: 10, experience: 9, evidence: 10, confidence: 9 },
      capabilities: ["OBSERVE", "REMEMBER"],
      evidenceStrengthWeight: 0.95,
      professionalMapping: {
        engineeringRoles: ["Systems Programmer", "Backend Engineer"],
        certifications: [],
        interviewDepth: "DEEP_DIVE",
        industrySectors: ["Systems", "FinTech"],
      },
    },
  },
  {
    id: "cgroups-namespaces",
    type: "concept",
    title: "Linux Namespaces & cgroups v2 Container Isolation",
    domain: "Operating Systems",
    importance: "CORE",
    maturity: "INDUSTRY",
    learningStatus: "VERIFIED",
    summary: "Linux process isolation primitives (PID, NET, MNT, IPC) and resource limit enforcement (CPU, Memory, I/O).",
    details: {
      definition: "Kernel mechanisms providing isolated process views (namespaces) and resource usage metering/limiting (cgroups).",
      engineeringPurpose: "Forms the foundational isolation boundary underlying container runtimes.",
      dependents: ["containers", "k8s-cni-networking"],
      tools: ["unshare", "nsenter", "cgtop"],
      operatingSystems: ["Linux"],
      competency: { knowledge: 9, experience: 8, evidence: 8, confidence: 8 },
      capabilities: ["REASON"],
      evidenceStrengthWeight: 0.90,
      professionalMapping: {
        engineeringRoles: ["Platform Engineer", "Containers SRE"],
        certifications: ["CKA"],
        interviewDepth: "DEEP_DIVE",
        industrySectors: ["Cloud Infrastructure"],
      },
    },
  },

  // =========================================================================
  // 3. DISTRIBUTED SYSTEMS CONCEPTS
  // =========================================================================
  {
    id: "raft-consensus",
    type: "concept",
    title: "Raft Distributed Consensus & State Machine Replication",
    domain: "Distributed Systems",
    importance: "ADVANCED",
    maturity: "INDUSTRY",
    learningStatus: "PRACTICING",
    summary: "Strong leader election, log replication, term numbers, and safety under network partitions.",
    details: {
      definition: "Consensus algorithm designed for understandability, equivalent to Paxos in fault tolerance and performance.",
      engineeringPurpose: "Ensures replicated state machine consistency across distributed cluster nodes.",
      problemsSolved: ["Split-brain prevention via quorum voting", "Automated failover during node crashes"],
      prerequisites: ["tcp-ip-stack", "cap-theorem"],
      dependents: ["k8s-cni-networking"],
      algorithms: ["Raft Leader Election", "Log Matching Property"],
      tools: ["etcd", "Consul", "HashiCorp Raft"],
      languages: ["Go", "Rust", "C++"],
      companiesUsingIt: ["HashiCorp", "Kubernetes (etcd)", "CockroachDB"],
      associatedProjects: ["cosmohub"],
      competency: { knowledge: 8, experience: 6, evidence: 7, confidence: 7 },
      capabilities: ["REASON", "RECOMMEND"],
      evidenceStrengthWeight: 0.85,
      professionalMapping: {
        engineeringRoles: ["Distributed Systems Engineer", "Database Infrastructure Engineer"],
        certifications: [],
        interviewDepth: "DEEP_DIVE",
        industrySectors: ["Cloud Infrastructure", "Databases"],
      },
    },
  },
  {
    id: "cap-theorem",
    type: "concept",
    title: "CAP Theorem & Distributed State Tradeoffs",
    domain: "Distributed Systems",
    importance: "CORE",
    maturity: "INDUSTRY",
    learningStatus: "VERIFIED",
    summary: "Consistency vs. Availability tradeoffs under network partition (P), eventual consistency, and PACELC extension.",
    details: {
      definition: "Theorem stating a distributed data store can only simultaneously guarantee two of Consistency, Availability, and Partition Tolerance.",
      engineeringPurpose: "Guides trade-off decisions when designing fault-tolerant distributed data storage.",
      dependents: ["raft-consensus"],
      competency: { knowledge: 9, experience: 7, evidence: 8, confidence: 8 },
      capabilities: ["REASON"],
      evidenceStrengthWeight: 0.90,
      professionalMapping: {
        engineeringRoles: ["Systems Architect", "Backend Engineer"],
        certifications: [],
        interviewDepth: "INTERMEDIATE",
        industrySectors: ["Software Architecture"],
      },
    },
  },

  // =========================================================================
  // 4. SOFTWARE ARCHITECTURE & BACKEND CONCEPTS
  // =========================================================================
  {
    id: "repository-pattern",
    type: "concept",
    title: "Repository & Decoupled Data Access Pattern",
    domain: "Software Architecture",
    importance: "CORE",
    maturity: "INDUSTRY",
    learningStatus: "MASTERED",
    summary: "Decouples domain logic from persistence mechanisms through strongly-typed data provider interfaces.",
    details: {
      definition: "Architectural pattern mediating between domain and data mapping layers using a collection-like interface.",
      engineeringPurpose: "Enables persistence-agnostic domain logic and clean unit testing.",
      dependents: ["devan-os"],
      languages: ["TypeScript", "C#", "Java"],
      associatedProjects: ["devan-os", "ujwal-portfolio"],
      competency: { knowledge: 10, experience: 10, evidence: 10, confidence: 10 },
      capabilities: ["OBSERVE", "REMEMBER", "REASON"],
      evidenceStrengthWeight: 1.0,
      professionalMapping: {
        engineeringRoles: ["Software Architect", "Lead Backend Engineer"],
        certifications: [],
        interviewDepth: "DEEP_DIVE",
        industrySectors: ["Software Engineering"],
      },
    },
  },

  // =========================================================================
  // 5. SECURITY & CRYPTOGRAPHY CONCEPTS
  // =========================================================================
  {
    id: "tls-13-handshake",
    type: "concept",
    title: "TLS 1.3 Cryptographic Handshake & Forward Secrecy",
    domain: "Security",
    importance: "CORE",
    maturity: "INDUSTRY",
    learningStatus: "VERIFIED",
    summary: "RFC 8446 1-RTT cryptographic handshake, ECDHE key exchange, AES-256-GCM authenticated encryption, and PKI validation.",
    details: {
      definition: "Modern cryptographic transport protocol providing privacy, data integrity, and server authentication over TCP.",
      engineeringPurpose: "Secures web and RPC communication against eavesdropping and tampering.",
      prerequisites: ["tcp-ip-stack", "pki-x509-certificates"],
      rfcs: ["RFC 8446"],
      tools: ["openssl", "tshark"],
      libraries: ["OpenSSL", "rustls"],
      associatedExperiments: ["networking-protocol-pipeline"],
      competency: { knowledge: 9, experience: 8, evidence: 9, confidence: 8 },
      capabilities: ["OBSERVE", "REASON"],
      evidenceStrengthWeight: 0.90,
      professionalMapping: {
        engineeringRoles: ["Security Engineer", "Network Engineer"],
        certifications: ["CISSP"],
        interviewDepth: "DEEP_DIVE",
        industrySectors: ["Cybersecurity", "FinTech"],
      },
    },
  },

  // =========================================================================
  // 6. AI SYSTEMS & MACHINE LEARNING CONCEPTS
  // =========================================================================
  {
    id: "vector-search-ann",
    type: "concept",
    title: "Vector Search & ANN Embedding Indexing",
    domain: "AI Systems",
    importance: "ADVANCED",
    maturity: "INDUSTRY",
    learningStatus: "VERIFIED",
    summary: "Approximate Nearest Neighbor indexing (HNSW), 384-dim Float32 vector embeddings, and SIMD-accelerated Cosine similarity.",
    details: {
      definition: "Algorithmic search for high-dimensional vectors representing semantic meaning in vector space.",
      engineeringPurpose: "Enables semantic document retrieval, recommendation, and RAG pipelines.",
      tools: ["Pinecone", "Milvus", "Qdrant", "ONNX Runtime"],
      associatedProjects: ["cineforge-ai-pro", "devan-os"],
      associatedExperiments: ["vector-search-benchmark"],
      competency: { knowledge: 9, experience: 8, evidence: 9, confidence: 8 },
      capabilities: ["REASON", "RECOMMEND"],
      evidenceStrengthWeight: 0.90,
      professionalMapping: {
        engineeringRoles: ["AI Systems Engineer", "MLOps Engineer"],
        certifications: [],
        interviewDepth: "DEEP_DIVE",
        industrySectors: ["AI Systems", "Search"],
      },
    },
  },

  // =========================================================================
  // 7. PROJECTS & REPOSITORIES (REFERENCING CONCEPTS)
  // =========================================================================
  {
    id: "devan-os",
    type: "project",
    title: "DEVAN Engineering Intelligence OS",
    domain: "Operating Systems",
    summary: "Engineering cognitive operating system modeling, reasoning, and evolving Ujwal's professional intelligence.",
  },
  {
    id: "cineforge-ai-pro",
    type: "project",
    title: "CineForge AI Pro",
    domain: "AI Systems",
    summary: "Bilingual AI pre-production video generation engine with local vector search.",
  },
  {
    id: "cosmohub",
    type: "project",
    title: "CosmoHub",
    domain: "Distributed Systems",
    summary: "Real-time astronomical telemetry and dataset aggregation platform.",
  },
  {
    id: "repo-devan2",
    type: "repository",
    title: "kantimohanthy/Devan2",
    domain: "Cloud",
    summary: "Primary GitHub repository storing DEVAN OS codebase and automated Vitest test suite.",
  },
];

export const CANONICAL_RELATIONSHIPS: OntologyRelationship[] = [
  // Concept-to-Concept Dependencies & Prerequisites
  { fromId: "dns-iterative-resolution", toId: "tcp-ip-stack", type: "DEPENDS_ON", note: "DNS queries travel over UDP/TCP port 53" },
  { fromId: "tls-13-handshake", toId: "tcp-ip-stack", type: "DEPENDS_ON", note: "TLS 1.3 requires established TCP transport" },
  { fromId: "bgp-routing", toId: "tcp-ip-stack", type: "DEPENDS_ON", note: "BGP-4 uses TCP port 179" },
  { fromId: "longley-rice-itm", toId: "tvws-rf-propagation", type: "PREREQUISITE_FOR", note: "ITM terrain algorithm models TVWS path loss" },
  { fromId: "olsr-mesh-routing", toId: "tvws-rf-propagation", type: "RELATED_TO", note: "OLSR mesh protocol routes traffic over TVWS links" },
  { fromId: "cgroups-namespaces", toId: "linux-ebpf-telemetry", type: "RELATED_TO", note: "eBPF monitors container cgroups" },
  { fromId: "posix-sockets", toId: "tcp-ip-stack", type: "PREREQUISITE_FOR", note: "POSIX sockets wrap TCP/IP streams" },
  { fromId: "raft-consensus", toId: "tcp-ip-stack", type: "DEPENDS_ON", note: "Raft consensus RPCs travel over TCP/IP" },
  { fromId: "cap-theorem", toId: "raft-consensus", type: "PREREQUISITE_FOR", note: "CAP theorem dictates Raft CP partition behavior" },

  // Projects reference Concepts
  { fromId: "devan-os", toId: "linux-ebpf-telemetry", type: "IMPLEMENTS" },
  { fromId: "devan-os", toId: "vector-search-ann", type: "IMPLEMENTS" },
  { fromId: "devan-os", toId: "repository-pattern", type: "IMPLEMENTS" },
  { fromId: "cineforge-ai-pro", toId: "vector-search-ann", type: "IMPLEMENTS" },
  { fromId: "cosmohub", toId: "raft-consensus", type: "IMPLEMENTS" },

  // Evidence Anchors reference Concepts
  { fromId: "repo-devan2", toId: "devan-os", type: "EVIDENCE_FOR" },
];
