import {
  OntologyEntity,
  OntologyClaim,
  EvidenceLedgerEntry,
  OntologyMission,
  SemanticRelationship,
  ReasoningReplayTrace,
} from "./types";

export const ONTOLOGY_ENTITIES: OntologyEntity[] = [
  {
    id: "rfc1035",
    name: "RFC 1035",
    type: "paper",
    domain: "Networking",
    status: "VERIFIED",
    confidence: 98,
    description: "Domain Names: Implementation and Specification. Foundational DNS spec.",
    firstUsed: "2025",
    experimentsCount: 15,
    relatedEntityIds: ["dns", "dig", "tshark"],
  },
  {
    id: "dns",
    name: "DNS Resolution",
    type: "concept",
    domain: "Networking",
    status: "DEFENDED",
    confidence: 97,
    description: "Hierarchical distributed database resolving hostnames to IP addresses.",
    firstUsed: "2024",
    experimentsCount: 23,
    relatedEntityIds: ["rfc1035", "dig", "tshark", "cosmohub"],
  },
  {
    id: "dig",
    name: "dig",
    type: "tool",
    domain: "Networking",
    status: "VERIFIED",
    confidence: 99,
    description: "DNS lookup utility for querying Domain Name System name servers.",
    firstUsed: "2025",
    experimentsCount: 23,
    relatedEntityIds: ["dns", "rfc1035"],
  },
  {
    id: "tshark",
    name: "tshark / Wireshark",
    type: "tool",
    domain: "Networking",
    status: "VERIFIED",
    confidence: 98,
    description: "Command-line packet analyzer capturing raw network datagrams.",
    firstUsed: "2025",
    experimentsCount: 18,
    relatedEntityIds: ["dns", "dig"],
  },
  {
    id: "cineforge",
    name: "CineForge AI Pro",
    type: "project",
    domain: "AI",
    status: "VERIFIED",
    confidence: 94,
    description: "Bilingual AI pre-production assistant built on Hugging Face & watsonx.",
    firstUsed: "2026",
    experimentsCount: 12,
    relatedEntityIds: ["sentinel"],
  },
  {
    id: "cosmohub",
    name: "CosmoHub",
    type: "project",
    domain: "Space",
    status: "IN_TESTING",
    confidence: 85,
    description: "Ontology-driven intelligence layer for the global space economy.",
    firstUsed: "2026",
    experimentsCount: 8,
    relatedEntityIds: ["dns"],
  },
];

export const ONTOLOGY_CLAIMS: OntologyClaim[] = [
  {
    id: "claim-dns-referral",
    statement: "Iterative DNS resolution follows four referral stages without recursive flags.",
    status: "VERIFIED",
    evidenceCount: 12,
    confidence: 97,
    lastTested: "Aug 2026",
    domain: "Networking",
    supportingExperimentIds: ["exp-dig-trace-001", "networking-protocol-pipeline"],
  },
  {
    id: "claim-doh-tamper-resistance",
    statement: "DoH resolution incurs ~10ms HTTPS overhead vs raw UDP/53 but guarantees MITM tamper resistance.",
    status: "VERIFIED",
    evidenceCount: 8,
    confidence: 95,
    lastTested: "Aug 2026",
    domain: "Networking",
    supportingExperimentIds: ["networking-protocol-pipeline"],
  },
  {
    id: "claim-simd-vector-precision",
    statement: "Client-side 384-dim ONNX vector similarity loop achieves sub-20ms precision with Float32 SIMD.",
    status: "VERIFIED",
    evidenceCount: 14,
    confidence: 92,
    lastTested: "Aug 2026",
    domain: "AI",
    supportingExperimentIds: ["vector-search-benchmark"],
  },
];

export const EVIDENCE_LEDGER: EvidenceLedgerEntry[] = [
  {
    id: "ev-0042",
    code: "Evidence #0042",
    question: "Does dig +trace send recursive queries?",
    method: "Packet capture & socket trace",
    artifacts: ["dns-trace-001.pcap", "dig-trace-001.log"],
    result: "RD bit = 0 on iterative referral hops",
    confidence: 99,
    verified: true,
    timestamp: "2026-08-07 09:12:04",
  },
  {
    id: "ev-0043",
    code: "Evidence #0043",
    question: "What is the DoH TLS handshake duration on Cloudflare endpoint?",
    method: "Multi-span telemetry profiler",
    artifacts: ["protocol-trace.json"],
    result: "24 ms TLS 1.3 handshake duration",
    confidence: 98,
    verified: true,
    timestamp: "2026-08-07 08:42:18",
  },
  {
    id: "ev-0044",
    code: "Evidence #0044",
    question: "What is the cosine similarity execution speed for 384-dim Float32 vectors?",
    method: "SIMD micro-benchmark loop",
    artifacts: ["vector-search-benchmark.log"],
    result: "14.5 ms for 1,000 vector iterations",
    confidence: 94,
    verified: true,
    timestamp: "2026-08-06 18:30:10",
  },
];

export const ONTOLOGY_MISSIONS: OntologyMission[] = [
  {
    id: "mission-dns-resolver",
    title: "DNS Protocol Mechanics",
    objective: "Understand DNS from packet to resolver implementation.",
    progressPercent: 72,
    domain: "Networking",
    subtasks: [
      { id: "st-1", label: "RFC 1034 Spec Review", completed: true },
      { id: "st-2", label: "RFC 1035 Wire Format Decoding", completed: true },
      { id: "st-3", label: "dig +trace Iterative Analysis", completed: true },
      { id: "st-4", label: "tcpdump / tshark PCAP Capture", completed: true },
      { id: "st-5", label: "Wireshark Wire Packet Inspection", completed: true },
      { id: "st-6", label: "DNSSEC Validation Protocol", completed: false },
      { id: "st-7", label: "EDNS0 Extension Opt Records", completed: false },
      { id: "st-8", label: "Root Hints & BIND Source Inspection", completed: false },
    ],
  },
  {
    id: "mission-vector-search",
    title: "In-Browser Semantic Search",
    objective: "Build a zero-backend WASM ONNX vector similarity engine.",
    progressPercent: 85,
    domain: "AI",
    subtasks: [
      { id: "st-v1", label: "all-MiniLM-L6-v2 ONNX Download", completed: true },
      { id: "st-v2", label: "WebAssembly Transformer Pipeline", completed: true },
      { id: "st-v3", label: "Float32 SIMD Dot Product", completed: true },
      { id: "st-v4", label: "Hybrid BM25 + Vector Ranker", completed: true },
      { id: "st-v5", label: "LRU Embedding Cache Persistence", completed: false },
    ],
  },
];

export const SEMANTIC_RELATIONSHIPS: SemanticRelationship[] = [
  { fromId: "dig", toId: "dns", type: "USES" },
  { fromId: "tshark", toId: "dns", type: "VALIDATES" },
  { fromId: "dns", toId: "rfc1035", type: "IMPLEMENTS" },
  { fromId: "cosmohub", toId: "dns", type: "DEPENDS_ON" },
  { fromId: "cineforge", toId: "sentinel", type: "INSPIRED_BY" },
];

export const REASONING_REPLAY_TRACES: Record<string, ReasoningReplayTrace> = {
  "claim-dns-referral": {
    claimId: "claim-dns-referral",
    title: "Reasoning Replay: Iterative DNS Resolution Referral Stages",
    steps: [
      { stage: "Claim", detail: "Iterative DNS resolution follows four referral stages without recursive flags.", timestamp: "08:00:00", status: "info" },
      { stage: "Question", detail: "How many hops does dig +trace example.com actually show for a real domain?", timestamp: "08:05:00", status: "info" },
      { stage: "Hypothesis", detail: "dig +trace will execute 4 hops: Root -> TLD -> Authoritative -> Final Answer with RD=0.", timestamp: "08:10:00", status: "info" },
      { stage: "Sources", detail: "RFC 1035 section 3.3.11 & Kurose & Ross Chapter 2.", timestamp: "08:15:00", status: "info", artifactRef: "src-rfc1035" },
      { stage: "Experiment", detail: "dig +trace example.com captured alongside tshark -i eth0 -f 'port 53' -w dns-trace.pcap.", timestamp: "08:30:00", status: "info", artifactRef: "exp-dig-trace-001" },
      { stage: "Terminal Recording", detail: "Captured 4 hop responses: a.root-servers.net -> a.gtld-servers.net -> a.iana-servers.net.", timestamp: "08:45:00", status: "pass", artifactRef: "/evidence/dns/dig-trace-001.log" },
      { stage: "Packet Capture", detail: "Recorded dns-trace.pcap containing 8 UDP port 53 datagrams.", timestamp: "09:00:00", status: "pass", artifactRef: "/evidence/dns/dns-trace-001.pcap" },
      { stage: "Observations", detail: "Header RD (Recursion Desired) bit was 0 on all iterative referral queries.", timestamp: "09:05:00", status: "pass" },
      { stage: "Mistakes", detail: "systemd-resolved loopback cache masked Hop 1 initially; resolved via -i any interface flag.", timestamp: "09:10:00", status: "warn" },
      { stage: "Conclusion", detail: "Hypothesis confirmed with 100% wire-level fidelity.", timestamp: "09:12:00", status: "pass" },
      { stage: "Confidence", detail: "Upgraded claim confidence score to 97%.", timestamp: "09:15:00", status: "pass" },
      { stage: "Knowledge Graph Updated", detail: "Derived state promoted from IMPLEMENTED to TESTED & DEFENDED.", timestamp: "09:31:00", status: "pass" },
    ],
  },
};

export const COGNITIVE_METRICS = {
  domains: 14,
  evidenceRecords: 236,
  experiments: 91,
  artifacts: 1482,
  verifiedClaims: 64,
  repositories: 19,
  booksIndexed: 37,
  researchPapers: 112,
  knowledgeConnections: 3487,
};
