-- Enable Row Level Security (RLS) on all application domain tables
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RefreshToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Project" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Technology" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectTechnology" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Skill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Experience" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Education" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProtocolTrace" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Experiment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Repository" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Mission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Concept" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Decision" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserConceptCompetency" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExperienceEvent" ENABLE ROW LEVEL SECURITY;

-- Revoke PostgREST Data API access from unprivileged anon and authenticated roles
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
